### ISSUE TITLE
(feature:folder_structure_refactoring)argparser test/train 확인

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/YOLOv1#36]

**Comment by insurgent92** [comment]
확인(https://cs230-stanford.github.io/pytorch-getting-started.html#code-layout)
확인(https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md)

**Comment by ssaru** [comment]
argparser train test 코드 나누는 것은 제가 했습니다.
