### ISSUE TITLE
Box size loss에 sqrt가 들어가니까 이를 어디서 제곱해야할지 생각

### ISSUE THREAD

**Issue by ssaru** [DeepBaksuVision/YOLOv1#43]

**Comment by ssaru** [comment]
Output(실수)에 sqrt 적용시, box크기는 상대적으로 커지나, box가 object에 잘 맞지는 않음

![figure_7](https://user-images.githubusercontent.com/13328380/47965861-7f91b200-e08f-11e8-82f2-77d1badb26ad.png)
![figure_6](https://user-images.githubusercontent.com/13328380/47965862-7f91b200-e08f-11e8-868f-5de0bd625cf5.png)
![figure_5](https://user-images.githubusercontent.com/13328380/47965863-802a4880-e08f-11e8-8668-8651be1cbf73.png)
![figure_4](https://user-images.githubusercontent.com/13328380/47965864-802a4880-e08f-11e8-8d67-40f8d5fdb7fb.png)
![figure_3](https://user-images.githubusercontent.com/13328380/47965865-802a4880-e08f-11e8-97b6-04f351bde6e5.png)
![figure_2](https://user-images.githubusercontent.com/13328380/47965866-80c2df00-e08f-11e8-8bcb-0fbe730474a7.png)
![figure_1](https://user-images.githubusercontent.com/13328380/47965867-80c2df00-e08f-11e8-840c-faa6771f58c9.png)

**Comment by ssaru** [comment]
output(실수)에 numpy.power(x,2)를 했을 때, box가 상대적으로 많이 작아짐

![figure_7](https://user-images.githubusercontent.com/13328380/47965906-df885880-e08f-11e8-8f90-1d884786595e.png)
![figure_6](https://user-images.githubusercontent.com/13328380/47965907-df885880-e08f-11e8-8c6b-eef2df954110.png)
![figure_5](https://user-images.githubusercontent.com/13328380/47965908-df885880-e08f-11e8-8d66-7021c6a953ec.png)
![figure_4](https://user-images.githubusercontent.com/13328380/47965909-df885880-e08f-11e8-835a-82d65ae0ae44.png)
![figure_3](https://user-images.githubusercontent.com/13328380/47965910-e020ef00-e08f-11e8-9028-17e3d896ba49.png)
![figure_2](https://user-images.githubusercontent.com/13328380/47965911-e020ef00-e08f-11e8-888d-0df5518249b8.png)
![figure_1](https://user-images.githubusercontent.com/13328380/47965913-e020ef00-e08f-11e8-8882-0bce2e6420f3.png)

**Comment by insurgent92** [comment]
확인했습니다. 저도 알아보도록 하겠습니다.
